# Generated by Django 5.2.3 on 2025-08-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('expire_date', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=30)),
                ('costumer_phone', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottel_type', models.CharField(max_length=50)),
                ('bottel_size', models.CharField(max_length=50)),
                ('expire_date_bottel', models.DateField()),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saller.saller')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=300)),
                ('costumer_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bottel_type', models.CharField(max_length=50)),
                ('bottel_size', models.CharField(max_length=50)),
                ('expire_date_bottel', models.DateField()),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saller.saller')),
            ],
        ),
    ]
