# Generated by Django 5.2.3 on 2025-08-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saller',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
