# Generated by Django 5.2.3 on 2025-08-22 18:09

import saller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saller', '0002_saller_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saller',
            name='expire_date',
            field=models.DateField(default=saller.models.three_years_from_now),
        ),
    ]
